name: tuyau

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: self-hosted
  workflow_dispatch: # <--- Ajoute cette ligne pour activer le bouton manuel
    inputs:
      reason:
        description: 'Raison du déploiement manuel'
        required: false
        default: 'azy'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: kill old container 
        run : sudo docker kill github-runner
      
      - name: create new container 
        run : sudo docker run --detach --rm -p 80:80 --name kebab-web -t 5f9e7f39dee4 
