name: tuyau

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch: # pour le lancement manuel
    inputs:
      reason:
        description: 'Raison du déploiement manuel'
        required: false
        default: 'azy'
jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: kill old container 
        run : sudo .github/workflows/./create_container.sh
